/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package habib_046_b;

/**
 *
 * @author Ahmad Habib
 */
import javax.swing.JOptionPane;
import java.io.*;
public class koreksi extends javax.swing.JFrame {

    /**
     * Creates new form koreksi
     */
    public koreksi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        soal1 = new javax.swing.JLabel();
        soal2 = new javax.swing.JLabel();
        soal3 = new javax.swing.JLabel();
        soal4 = new javax.swing.JLabel();
        skor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("masukan nama yang inign dikoreksi");

        jButton1.setText("cari dan periksa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        soal1.setText("soal no 1 : ");

        soal2.setText("soal no 2 : ");

        soal3.setText("soal no 3 : ");

        soal4.setText("soal no 4 :");

        skor.setText("skor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(soal1)
                            .addComponent(soal2)
                            .addComponent(soal3)
                            .addComponent(soal4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(skor)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(soal1)
                .addGap(18, 18, 18)
                .addComponent(soal2)
                .addGap(18, 18, 18)
                .addComponent(soal3)
                .addGap(18, 18, 18)
                .addComponent(soal4)
                .addGap(18, 18, 18)
                .addComponent(skor)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
int benar = 0; 
String idsiswa = jTextField1.getText();

try{
FileInputStream fis = new FileInputStream("C:\\KULIAH\\PELAJARAN KULIAH SEMESTER 4\\dataujian\\"+idsiswa+".txt");
ObjectInputStream ois = new ObjectInputStream(fis);
jawaban aaa = (jawaban) ois.readObject();

if(aaa.jawaban1.equals("abubakar")==true){
benar += 20;
soal1.setText("jawaban no1 = "+aaa.jawaban1+", jawaban benar");
}else if(aaa.jawaban1.equals("umar")==true){
benar -= 10;
soal1.setText("jawaban soal 1 = "+aaa.jawaban1+", jawaban salah ");
}else{
soal1.setText("jawaban dikosongkan ");
}

if(aaa.jawaban2.equals("komunisme")==true){
benar += 20;
soal2.setText("jawaban no1 = "+aaa.jawaban2+", jawaban benar");
}else if(aaa.jawaban2.equals("kapitalisme")==true){
benar -= 10;
soal2.setText("jawaban soal 1 = "+aaa.jawaban2+", jawaban salah ");
}else{
soal2.setText("jawaban dikosongkan ");
}

if(aaa.jawaban3.equals("sekuler")==true){
benar += 20;
soal3.setText("jawaban no1 = "+aaa.jawaban3+", jawaban benar");
}else if(aaa.jawaban3.equals("matrealis")==true){
benar -= 10;
soal3.setText("jawaban soal 1 = "+aaa.jawaban3+", jawaban salah ");
}else{
soal3.setText("jawaban dikosongkan ");
}

if(aaa.jawaban4.equals("thariq")==true){
benar += 20;
soal4.setText("jawaban no1 = "+aaa.jawaban4+", jawaban benar");
}else if(aaa.jawaban4.equals("alfatih")==true){
benar -= 10;
soal4.setText("jawaban soal 1 = "+aaa.jawaban4+", jawaban salah ");
}else{
soal4.setText("jawaban dikosongkan ");
}

skor.setText("total skor yang didapat : "+benar);

}catch(Exception e){
JOptionPane.showMessageDialog(null,e);
}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(koreksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(koreksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(koreksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(koreksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new koreksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel skor;
    private javax.swing.JLabel soal1;
    private javax.swing.JLabel soal2;
    private javax.swing.JLabel soal3;
    private javax.swing.JLabel soal4;
    // End of variables declaration//GEN-END:variables
}
